version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    platform: linux/amd64
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env
    volumes:
      - ./inputFile:/csvserver/inputdata
  prometheus:
    image: prom/prometheus:v2.45.2
    platform: linux/amd64
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

